### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by XDqrkneZ** [jasonwynn10/MyPlot#117]
how can I make the max plots to one instead of two?

**Comment by jasonwynn10** [comment]
What do you mean?

**Comment by XDqrkneZ** [comment]
like there's a maximum plot they can buy which is 2, how do i make it 1?

**Comment by jasonwynn10** [comment]
Does no one read how to actually use the plugin 🤦‍♂️ 
https://jasonwynn10.github.io/MyPlot/cmdsandperms

**Comment by XDqrkneZ** [comment]
what? I'm asking how can I limit how many plots a player can buy. The current limit is 2. How can I make it 1?

**Comment by jasonwynn10** [comment]
Maybe read the instructions on that link I gave you...

**Comment by Aericio** [comment]
![image](https://user-images.githubusercontent.com/16523741/32155641-99048fd2-bcdc-11e7-962e-86c0ccdb1e55.png)

Example: setting the user perm to `myplot.claimplots.1` will only allow users to claim a single plot instead of the default amount (2). `myplot.claimplots.x` can be replaced with any number (x)
