### ISSUE TITLE
Trusting on a part of the road

### ISSUE THREAD

**Issue by Wertzui123** [jasonwynn10/MyPlot#209]
I woud like it, if you coud trust players on the road next to a plot, or at the whole road in the world (as an admin). So the players coud build on this part of the road, and the other things that you can do with a trust...

**Comment by Aericio** [comment]
It is not possible for normal users to modify roads next to their plots since it causes many conflicts. 

Also, there would be no reason for roads if they could build on the road, since that would just be apart of their plot.

You can give the permission node to allow the user to edit ALL roads in the plot world, though.

myplot.admin.build.road
